Feature community
Melbourne-Backpack/melbourne-backpack pull request #2
Opened 2022-03-26 10:07 UTC by rider3458

Community screen with hard-coded data. The filter function is not usable yet.

2022-03-27 13:07 UTC, tnathu-ai reviewed
Decent job. Please add comments on the code

2022-03-27 15:16 UTC, doanyennhi requested changes
The Community heading and filter button are not aligned

2022-03-28 02:27 UTC, hlinh88 submitted a review, later dismissed
try flat list.

2022-03-28 05:25 UTC, doanyennhi approved these changes, later dismissed

2022-03-28 05:27 UTC, hlinh88 approved these changes

2022-03-28 05:28 UTC, doanyennhi approved these changes

2022-03-28 05:28 UTC, merged